Integrationtest (#3)
* integration testing

* sudo needed for dpkg

* DWHIMAGENAMESPACE declared

* reduce time to wait for wildfly

* .deb integration test

* apt update + i2b2 install

* quiet wget force install

* install dependencies

* no success connection

* dpkg allow failure

* dpkg install one package per call

* install deps with gdebi

* libapache2-mod-php version

* separate install of libapache-mod-php7.4

* .

* assume yes

* .

* fix broken

* remove sury

* .

* remove r packages

* remove all php and r

* preintsall postgres

* check db conn

* ensure postgres started

* ensure postgres started and enabled

* error if database unavailable

* find only latest

* wait for db

* wait for postgres service to be available

* .

* service name

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,6 +1,14 @@
 #!/bin/bash
 set -e
 
+readonly RES='\e[0m'
+readonly RED='\e[0;31m'
+readonly GRE='\e[0;32m'
+readonly YEL='\e[0;33m'
+readonly BRED='\e[1;31m'
+readonly BGRE='\e[1;32m'
+readonly BYEL='\e[1;33m'
+
 . /usr/share/debconf/confmodule
 DEBCONF_NAME=$(echo $DPKG_MAINTSCRIPT_PACKAGE | awk -F '-' '{print $1"-"$2}')
 
@@ -26,6 +34,19 @@ else
 	PSQL="psql postgresql://$user:$pass@$host:$port?sslmode=require"
 	echo "Connecting to postgres via TCP/IP to $host:$port."
 fi
+
+WAITCOUNT=0
+while ! systemctl start postgresql.service 2>/dev/null; do
+	if [ $WAITCOUNT -lt 12 ]; then
+		echo -e "${BRED}Database not yet installed. Waiting ...${RES}"
+		((WAITCOUNT++))
+		sleep 5
+	else
+		echo -e "${BRED}Database not yet installed. Aborting ...${RES}"
+		exit 1
+	fi
+done
+systemctl enable postgresql.service
 
 if  [[ $(eval "$PSQL -l" | grep "aktin" | wc -l) == 0 ]]; then
 
